services:
  server:
    build: ./server
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/prisma/dev.db:/app/prisma/dev.db

  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - '80:80'
